title: Jawad Mehmood Butt # your name (or website title) here
logo: "" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a robotics researcher and engineer. The active research areas are bio-inspired robotics, adaptive controls, and learning-driven controls. Besides, i develop software for STM32 driven emnedded applications.  
  <br><br>
  Traveled 8 countries around Asia and Europe. 
  <br><br>
  <a href="https://www.linkedin.com/in/jawad-butt-788a86138/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
